apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
   name: nginx-hpa
spec:
  scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: myngpod
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resources
      resource:
        name: cpu
        targetAverageUtilization: 5
