apiVersion: v1
kind: ReplicationController
metadata:
     name: myngpod
spec:
  replicas: 3
  template:
    metadata:
       labels:
         app: development
    spec:
     containers:
           - image: nginx
             name: ngcontainer
             ports:
               - containerPort: 80

